### ISSUE TITLE
Password Manager interferes with password entry

### ISSUE THREAD

**Issue by tmichalski** [lssinc/voyage-app-angular#13]
Steps to reproduce: 
* Mac Safari or Mac Chrome
* 1password installed in Safari or Chrome extensions
* Go to the login page of Voyage Banking app
* entering a password results in a "Password required" message with no form submission
* no way to get around this unless the password manager extension is removed

**Comment by tmichalski** [comment]
![screen shot 2017-09-21 at 2 28 00 pm](https://user-images.githubusercontent.com/104992/30714661-5548682a-9ed9-11e7-8ed4-887dbb4af2f9.png)

**Comment by raymer** [comment]
Fixed.
