### ISSUE TITLE
Profile image upload: resize and restrict

### ISSUE THREAD

**Issue by tmichalski** [lssinc/voyage-app-angular#14]
Since profile images are a fixed size / dimension, there should be some features and/or rules about how we handle the profile image on upload. 

Ideally we would:
* Allow any photo to be uploaded with a max size limit
* Once uploaded, display the profile image
* Allow the user to move a view finder over the image to select the visible portion of the image for display in the profile spot. 
* Crop the image and resize to no more than the maximum size allowed. 
* store the image and display in the upper right corner. 

Currently, any image can be display and it is forced into a height/width that bends and distorts the image on the Profile detail page, and sets the image to be off centered in the upper right corner. 

![screen shot 2017-09-21 at 2 33 40 pm](https://user-images.githubusercontent.com/104992/30714841-ec57dade-9ed9-11e7-9d26-73e2e63ac24e.png)

**Comment by raymer** [comment]
Done.
